// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQmlnxYwvayOk1Z2x_iJDXnoevuZdxquE',
    appId: '1:626447925100:web:29a2ca5e60d52fafe2fd49',
    messagingSenderId: '626447925100',
    projectId: 'first-ac7ef',
    authDomain: 'first-ac7ef.firebaseapp.com',
    storageBucket: 'first-ac7ef.appspot.com',
    measurementId: 'G-RMVPGWQ20P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTNjhXkak8PpaVmqBHaWmvaT7WFrhK3HI',
    appId: '1:626447925100:android:cc441778e594693be2fd49',
    messagingSenderId: '626447925100',
    projectId: 'first-ac7ef',
    storageBucket: 'first-ac7ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtbC2UwOSYDB4olvDqvc6gmtLwScceECA',
    appId: '1:626447925100:ios:6832b8b49580b226e2fd49',
    messagingSenderId: '626447925100',
    projectId: 'first-ac7ef',
    storageBucket: 'first-ac7ef.appspot.com',
    iosBundleId: 'com.example.firebaseBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtbC2UwOSYDB4olvDqvc6gmtLwScceECA',
    appId: '1:626447925100:ios:6832b8b49580b226e2fd49',
    messagingSenderId: '626447925100',
    projectId: 'first-ac7ef',
    storageBucket: 'first-ac7ef.appspot.com',
    iosBundleId: 'com.example.firebaseBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQmlnxYwvayOk1Z2x_iJDXnoevuZdxquE',
    appId: '1:626447925100:web:fa3acda86b264c01e2fd49',
    messagingSenderId: '626447925100',
    projectId: 'first-ac7ef',
    authDomain: 'first-ac7ef.firebaseapp.com',
    storageBucket: 'first-ac7ef.appspot.com',
    measurementId: 'G-6P2ZNFBVQ7',
  );

}